{% set name = "zodbpickle" %}
{% set version = "1.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "5fdfa84f05b25511a4e1190ec98728aa487e2eb6db016a951fdbb79bcc7307e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - toolchain

  run:
    - python
    - setuptools

test:
  imports:
    - zodbpickle
    - zodbpickle.tests

about:
  home: http://pypi.python.org/pypi/zodbpickle
  license: PSF 2 and ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Fork of Python 3 pickle module.'
  dev_url: https://github.com/zopefoundation/zodbpickle

extra:
  recipe-maintainers:
    - pmlandwehr
