{% set name = "zodbpickle" %}
{% set version = "1.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "6a60a2b996abea0d75ae1617c40229171834ff660527370bdd0c44645dda6906" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  preserve_egg_dir: True
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    
  host:
    - python
    - pip

  run:
    - python
    - setuptools

test:
  imports:
    - zodbpickle
    - zodbpickle.tests

about:
  home: http://pypi.python.org/pypi/zodbpickle
  license: PSF 2 and ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Fork of Python 3 pickle module.'
  dev_url: https://github.com/zopefoundation/zodbpickle

extra:
  recipe-maintainers:
    - pmlandwehr
