{% set name = "zodbpickle" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0d9930f46d41f086a763f40a12d014c46bbc5e19e728c8d66d7a06fef616739

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    
  host:
    - python
    - pip

  run:
    - python
    - setuptools

test:
  imports:
    - zodbpickle
    - zodbpickle.tests
  commands:
    - pip check
  requires: 
    - pip

about:
  home: http://pypi.python.org/pypi/zodbpickle
  license: ZPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Fork of Python 3 pickle module.'
  dev_url: https://github.com/zopefoundation/zodbpickle

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
