{% set name = "zodbpickle" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "95a247fb17bce980af8d548af70ac5bd1bad22773f242eb8efa24428efa909a8" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  preserve_egg_dir: True
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain

  run:
    - python

test:
  imports:
    - zodbpickle
    - zodbpickle.tests

about:
  home: http://pypi.python.org/pypi/zodbpickle
  license: PSF 2 and ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Fork of Python 3 pickle module.'
  dev_url: https://github.com/zopefoundation/zodbpickle

extra:
  recipe-maintainers:
    - pmlandwehr
