{% set name = "zodbpickle" %}
{% set version = "1.0.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "25d35f7c5ed95689d788b4da2a201990368b7abf032df0974632d0f8c5b39058" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    
  host:
    - python
    - pip

  run:
    - python
    - setuptools

test:
  imports:
    - zodbpickle
    - zodbpickle.tests

about:
  home: http://pypi.python.org/pypi/zodbpickle
  license: PSF 2 and ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Fork of Python 3 pickle module.'
  dev_url: https://github.com/zopefoundation/zodbpickle

extra:
  recipe-maintainers:
    - pmlandwehr
