# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EEvrEnjPecwThl3Oy80opaBSoygySpCtIv0b6NBBt8D1dci7uhsGqZ7PvTH6NrnY3euTCFDyLQjB6Ncl7+GyH6TZR6VrPCOGJoDv2g0BtyAtsqB6QM36QglzzUFG2Eylumx5Vvkh+DHu0DtaUAUHZ93Jw9/zPb+Vp77KtyIWQ6Igvqg078QOoPZgkz86ERhmCdYhekLtdOWC/gQ3W8QbHi6/KDO6+rycrnvPQykkdT3g+Ne50/y3yHNvPogb91X6uveALRgzwT3tdWS0xgMx+1lrSNTSe2Zna38xb3rbicxNlPUQ1X7e2v3pQGx6Q6UtQfmetSS+f4uP/dc3CvfNf5wvVAcCeGZBuXSTZHQPNMQ5Izb7r4z4WihIF6GJvHxujKxQL9CQOxiMfT+LGs9WkC/41UMixzr4E+K0PG+fn9yGYto7PoiznNQrZmkwbociQ+qOK5NJJRzZRCzo3kCcshV5RLZHvhVc4jvMwJUvffGK8ueP0/TFN5IFqehuawrq78rJyDsSEY45wVp83/sETLLyNDdaSTqjkOrKgSXopyqJ+Ojq9NglGBoymI6GtKaL5rI6o9Z/l6RuByteboHm5gpxqFxy5eKQqftU6V+zT9nwZeSRu8Q/AjQxwyNgLCB7O9Xr8MfjPCBXY+ElxgJ7ea3HcM1Vm822OZ+6Og+AG1Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
