travis:
  secure:
    BINSTAR_TOKEN: EEvrEnjPecwThl3Oy80opaBSoygySpCtIv0b6NBBt8D1dci7uhsGqZ7PvTH6NrnY3euTCFDyLQjB6Ncl7+GyH6TZR6VrPCOGJoDv2g0BtyAtsqB6QM36QglzzUFG2Eylumx5Vvkh+DHu0DtaUAUHZ93Jw9/zPb+Vp77KtyIWQ6Igvqg078QOoPZgkz86ERhmCdYhekLtdOWC/gQ3W8QbHi6/KDO6+rycrnvPQykkdT3g+Ne50/y3yHNvPogb91X6uveALRgzwT3tdWS0xgMx+1lrSNTSe2Zna38xb3rbicxNlPUQ1X7e2v3pQGx6Q6UtQfmetSS+f4uP/dc3CvfNf5wvVAcCeGZBuXSTZHQPNMQ5Izb7r4z4WihIF6GJvHxujKxQL9CQOxiMfT+LGs9WkC/41UMixzr4E+K0PG+fn9yGYto7PoiznNQrZmkwbociQ+qOK5NJJRzZRCzo3kCcshV5RLZHvhVc4jvMwJUvffGK8ueP0/TFN5IFqehuawrq78rJyDsSEY45wVp83/sETLLyNDdaSTqjkOrKgSXopyqJ+Ojq9NglGBoymI6GtKaL5rI6o9Z/l6RuByteboHm5gpxqFxy5eKQqftU6V+zT9nwZeSRu8Q/AjQxwyNgLCB7O9Xr8MfjPCBXY+ElxgJ7ea3HcM1Vm822OZ+6Og+AG1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
